# PR Type Labels
- name: feature
  color: '1D76DB'
  description: 'New functionality'

- name: bug
  color: 'D73A4A'
  description: "Something isn't working"

- name: hotfix
  color: 'B60205'
  description: 'Critical production fix'

- name: refactor
  color: '6F42C1'
  description: 'Code improvement without behavior change'

- name: performance
  color: '0E8A16'
  description: 'Performance improvement'

- name: accessibility
  color: '006B75'
  description: 'Accessibility improvement'

- name: chore
  color: 'FEF2C0'
  description: 'Maintenance task'

# Scope Labels
- name: ui
  color: 'FBCA04'
  description: 'UI components'

- name: animation
  color: 'FF6B6B'
  description: 'Animation-related changes'

- name: documentation
  color: '0075CA'
  description: 'Documentation changes'

- name: tests
  color: 'BFD4F2'
  description: 'Test changes'

- name: ci
  color: '5319E7'
  description: 'CI/CD changes'

- name: config
  color: 'D4C5F9'
  description: 'Configuration changes'

- name: github
  color: '333333'
  description: 'GitHub-specific files'

# Status Labels
- name: needs-review
  color: 'FFCC00'
  description: 'Awaiting code review'

- name: approved
  color: '0E8A16'
  description: 'Approved and ready to merge'

- name: changes-requested
  color: 'E99695'
  description: 'Changes have been requested'
